apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    cnrm.cloud.google.com/version: 1.5.0
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apiextensions.k8s.io/v1beta1","kind":"CustomResourceDefinition","metadata":{"annotations":{"cnrm.cloud.google.com/version":"1.5.0"},"creationTimestamp":null,"labels":{"cnrm.cloud.google.com/managed-by-kcc":"true","cnrm.cloud.google.com/system":"true","cnrm.cloud.google.com/tf2crd":"true"},"name":"computenodetemplates.compute.cnrm.cloud.google.com"},"spec":{"group":"compute.cnrm.cloud.google.com","names":{"categories":["gcp"],"kind":"ComputeNodeTemplate","plural":"computenodetemplates","shortNames":["gcpcomputenodetemplate","gcpcomputenodetemplates"],"singular":"computenodetemplate"},"scope":"Namespaced","validation":{"openAPIV3Schema":{"properties":{"apiVersion":{"description":"apiVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources","type":"string"},"kind":{"description":"kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds","type":"string"},"metadata":{"type":"object"},"spec":{"properties":{"description":{"description":"An optional textual description of the resource.","type":"string"},"nodeType":{"description":"Node type to use for nodes group that are created from this template.\nOnly one of nodeTypeFlexibility and nodeType can be specified.","type":"string"},"nodeTypeFlexibility":{"description":"Flexible properties for the desired node type. Node groups that\nuse this node template will create nodes of a type that matches\nthese properties. Only one of nodeTypeFlexibility and nodeType can\nbe specified.","properties":{"cpus":{"description":"Number of virtual CPUs to use.","type":"string"},"localSsd":{"description":"Use local SSD","type":"string"},"memory":{"description":"Physical memory available to the node, defined in MB.","type":"string"}},"type":"object"},"region":{"description":"Region where nodes using the node template will be created.\nIf it is not provided, the provider region is used.","type":"string"},"serverBinding":{"description":"The server binding policy for nodes using this template. Determines\nwhere the nodes should restart following a maintenance event.","properties":{"type":{"description":"Type of server binding policy. If 'RESTART_NODE_ON_ANY_SERVER',\nnodes using this template will restart on any physical server\nfollowing a maintenance event.\n\nIf 'RESTART_NODE_ON_MINIMAL_SERVER', nodes using this template\nwill restart on the same physical server following a maintenance\nevent, instead of being live migrated to or restarted on a new\nphysical server. This option may be useful if you are using\nsoftware licenses tied to the underlying server characteristics\nsuch as physical sockets or cores, to avoid the need for\nadditional licenses when maintenance occurs. However, VMs on such\nnodes will experience outages while maintenance is applied.","type":"string"}},"required":["type"],"type":"object"}},"type":"object"},"status":{"properties":{"conditions":{"description":"Conditions represents the latest available observation of the resource's current state.","items":{"properties":{"lastTransitionTime":{"description":"Last time the condition transitioned from one status to another.","type":"string"},"message":{"description":"Human-readable message indicating details about last transition.","type":"string"},"reason":{"description":"Unique, one-word, CamelCase reason for the condition's last transition.","type":"string"},"status":{"description":"Status is the status of the condition. Can be True, False, Unknown.","type":"string"},"type":{"description":"Type is the type of the condition.","type":"string"}},"type":"object"},"type":"array"},"creationTimestamp":{"description":"Creation timestamp in RFC3339 text format.","type":"string"},"selfLink":{"type":"string"}},"type":"object"}},"type":"object"}},"version":"v1beta1"},"status":{"acceptedNames":{"kind":"","plural":""},"conditions":[],"storedVersions":[]}}
  creationTimestamp: "2020-03-20T15:03:02Z"
  generation: 1
  labels:
    cnrm.cloud.google.com/managed-by-kcc: "true"
    cnrm.cloud.google.com/system: "true"
    cnrm.cloud.google.com/tf2crd: "true"
  name: computenodetemplates.compute.cnrm.cloud.google.com
  resourceVersion: "113849351"
  selfLink: /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/computenodetemplates.compute.cnrm.cloud.google.com
  uid: 2ac9b91a-57fe-4782-a1b7-73234034ea93
spec:
  conversion:
    strategy: None
  group: compute.cnrm.cloud.google.com
  names:
    categories:
    - gcp
    kind: ComputeNodeTemplate
    listKind: ComputeNodeTemplateList
    plural: computenodetemplates
    shortNames:
    - gcpcomputenodetemplate
    - gcpcomputenodetemplates
    singular: computenodetemplate
  preserveUnknownFields: true
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'apiVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            description:
              description: An optional textual description of the resource.
              type: string
            nodeType:
              description: |-
                Node type to use for nodes group that are created from this template.
                Only one of nodeTypeFlexibility and nodeType can be specified.
              type: string
            nodeTypeFlexibility:
              description: |-
                Flexible properties for the desired node type. Node groups that
                use this node template will create nodes of a type that matches
                these properties. Only one of nodeTypeFlexibility and nodeType can
                be specified.
              properties:
                cpus:
                  description: Number of virtual CPUs to use.
                  type: string
                localSsd:
                  description: Use local SSD
                  type: string
                memory:
                  description: Physical memory available to the node, defined in MB.
                  type: string
              type: object
            region:
              description: |-
                Region where nodes using the node template will be created.
                If it is not provided, the provider region is used.
              type: string
            serverBinding:
              description: |-
                The server binding policy for nodes using this template. Determines
                where the nodes should restart following a maintenance event.
              properties:
                type:
                  description: |-
                    Type of server binding policy. If 'RESTART_NODE_ON_ANY_SERVER',
                    nodes using this template will restart on any physical server
                    following a maintenance event.

                    If 'RESTART_NODE_ON_MINIMAL_SERVER', nodes using this template
                    will restart on the same physical server following a maintenance
                    event, instead of being live migrated to or restarted on a new
                    physical server. This option may be useful if you are using
                    software licenses tied to the underlying server characteristics
                    such as physical sockets or cores, to avoid the need for
                    additional licenses when maintenance occurs. However, VMs on such
                    nodes will experience outages while maintenance is applied.
                  type: string
              required:
              - type
              type: object
          type: object
        status:
          properties:
            conditions:
              description: Conditions represents the latest available observation
                of the resource's current state.
              items:
                properties:
                  lastTransitionTime:
                    description: Last time the condition transitioned from one status
                      to another.
                    type: string
                  message:
                    description: Human-readable message indicating details about last
                      transition.
                    type: string
                  reason:
                    description: Unique, one-word, CamelCase reason for the condition's
                      last transition.
                    type: string
                  status:
                    description: Status is the status of the condition. Can be True,
                      False, Unknown.
                    type: string
                  type:
                    description: Type is the type of the condition.
                    type: string
                type: object
              type: array
            creationTimestamp:
              description: Creation timestamp in RFC3339 text format.
              type: string
            selfLink:
              type: string
          type: object
      type: object
  version: v1beta1
  versions:
  - name: v1beta1
    served: true
    storage: true
status:
  acceptedNames:
    categories:
    - gcp
    kind: ComputeNodeTemplate
    listKind: ComputeNodeTemplateList
    plural: computenodetemplates
    shortNames:
    - gcpcomputenodetemplate
    - gcpcomputenodetemplates
    singular: computenodetemplate
  conditions:
  - lastTransitionTime: "2020-03-20T15:03:02Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: null
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1beta1
