apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apiextensions.k8s.io/v1beta1","kind":"CustomResourceDefinition","metadata":{"annotations":{},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile"},"name":"managedcertificates.networking.gke.io"},"spec":{"group":"networking.gke.io","names":{"kind":"ManagedCertificate","plural":"managedcertificates","shortNames":["mcrt"],"singular":"managedcertificate"},"scope":"Namespaced","validation":{"openAPIV3Schema":{"properties":{"spec":{"properties":{"domains":{"items":{"maxLength":63,"pattern":"^(([a-zA-Z0-9]+|[a-zA-Z0-9][-a-zA-Z0-9]*[a-zA-Z0-9])\\.)+[a-zA-Z][-a-zA-Z0-9]*[a-zA-Z0-9]\\.?$","type":"string"},"maxItems":1,"type":"array"}}},"status":{"properties":{"certificateName":{"type":"string"},"certificateStatus":{"type":"string"},"domainStatus":{"items":{"properties":{"domain":{"type":"string"},"status":{"type":"string"}},"required":["domain","status"],"type":"object"},"type":"array"},"expireTime":{"format":"date-time","type":"string"}}}}}},"version":"v1beta1"}}
  creationTimestamp: "2019-08-29T15:35:21Z"
  generation: 1
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
  name: managedcertificates.networking.gke.io
  resourceVersion: "84906258"
  selfLink: /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/managedcertificates.networking.gke.io
  uid: 9ccef5fe-ca72-11e9-a60a-4201ac100006
spec:
  additionalPrinterColumns:
  - JSONPath: .metadata.creationTimestamp
    description: |-
      CreationTimestamp is a timestamp representing the server time when this object was created. It is not guaranteed to be set in happens-before order across separate operations. Clients may not set this value. It is represented in RFC3339 form and is in UTC.

      Populated by the system. Read-only. Null for lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata
    name: Age
    type: date
  conversion:
    strategy: None
  group: networking.gke.io
  names:
    kind: ManagedCertificate
    listKind: ManagedCertificateList
    plural: managedcertificates
    shortNames:
    - mcrt
    singular: managedcertificate
  preserveUnknownFields: true
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            domains:
              items:
                maxLength: 63
                pattern: ^(([a-zA-Z0-9]+|[a-zA-Z0-9][-a-zA-Z0-9]*[a-zA-Z0-9])\.)+[a-zA-Z][-a-zA-Z0-9]*[a-zA-Z0-9]\.?$
                type: string
              maxItems: 1
              type: array
        status:
          properties:
            certificateName:
              type: string
            certificateStatus:
              type: string
            domainStatus:
              items:
                properties:
                  domain:
                    type: string
                  status:
                    type: string
                required:
                - domain
                - status
                type: object
              type: array
            expireTime:
              format: date-time
              type: string
  version: v1beta1
  versions:
  - name: v1beta1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ManagedCertificate
    listKind: ManagedCertificateList
    plural: managedcertificates
    shortNames:
    - mcrt
    singular: managedcertificate
  conditions:
  - lastTransitionTime: "2019-08-29T15:35:21Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: null
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  - lastTransitionTime: "2020-02-05T08:30:36Z"
    message: '[spec.validation.openAPIV3Schema.properties[spec].type: Required value:
      must not be empty for specified object fields, spec.validation.openAPIV3Schema.properties[status].type:
      Required value: must not be empty for specified object fields, spec.validation.openAPIV3Schema.type:
      Required value: must not be empty at the root]'
    reason: Violations
    status: "True"
    type: NonStructuralSchema
  storedVersions:
  - v1beta1
