apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apiextensions.k8s.io/v1beta1","kind":"CustomResourceDefinition","metadata":{"annotations":{},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile","app":"istio-pilot","heritage":"Tiller","istio":"rbac","k8s-app":"istio","release":"istio"},"name":"authorizationpolicies.rbac.istio.io"},"spec":{"group":"rbac.istio.io","names":{"categories":["istio-io","rbac-istio-io"],"kind":"AuthorizationPolicy","plural":"authorizationpolicies","singular":"authorizationpolicy"},"scope":"Namespaced","version":"v1alpha1"}}
  creationTimestamp: "2020-02-05T08:42:32Z"
  generation: 1
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    app: istio-pilot
    heritage: Tiller
    istio: rbac
    k8s-app: istio
    release: istio
  name: authorizationpolicies.rbac.istio.io
  resourceVersion: "84914271"
  selfLink: /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/authorizationpolicies.rbac.istio.io
  uid: 8b21e8b6-30a3-4814-b82a-bb2289b6c8b5
spec:
  conversion:
    strategy: None
  group: rbac.istio.io
  names:
    categories:
    - istio-io
    - rbac-istio-io
    kind: AuthorizationPolicy
    listKind: AuthorizationPolicyList
    plural: authorizationpolicies
    singular: authorizationpolicy
  preserveUnknownFields: true
  scope: Namespaced
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    categories:
    - istio-io
    - rbac-istio-io
    kind: AuthorizationPolicy
    listKind: AuthorizationPolicyList
    plural: authorizationpolicies
    singular: authorizationpolicy
  conditions:
  - lastTransitionTime: "2020-02-05T08:42:32Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: null
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1alpha1
