apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    helm.sh/hook: crd-install
    helm.sh/hook-delete-policy: before-hook-creation
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apiextensions.k8s.io/v1beta1","kind":"CustomResourceDefinition","metadata":{"annotations":{"helm.sh/hook":"crd-install","helm.sh/hook-delete-policy":"before-hook-creation"},"labels":{"app.kubernetes.io/name":"velero"},"name":"serverstatusrequests.velero.io"},"spec":{"group":"velero.io","names":{"kind":"ServerStatusRequest","plural":"serverstatusrequests"},"scope":"Namespaced","version":"v1"}}
  creationTimestamp: "2019-08-30T09:59:04Z"
  generation: 1
  labels:
    app.kubernetes.io/name: velero
  name: serverstatusrequests.velero.io
  resourceVersion: "70354307"
  selfLink: /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/serverstatusrequests.velero.io
  uid: ccbfa74f-cb0c-11e9-917e-4201ac100009
spec:
  conversion:
    strategy: None
  group: velero.io
  names:
    kind: ServerStatusRequest
    listKind: ServerStatusRequestList
    plural: serverstatusrequests
    singular: serverstatusrequest
  preserveUnknownFields: true
  scope: Namespaced
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ServerStatusRequest
    listKind: ServerStatusRequestList
    plural: serverstatusrequests
    singular: serverstatusrequest
  conditions:
  - lastTransitionTime: "2019-08-30T09:59:04Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: null
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1
