apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    components.gke.io/component-version: networkpolicy-calico-1.0.1
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apiextensions.k8s.io/v1beta1","kind":"CustomResourceDefinition","metadata":{"annotations":{"components.gke.io/component-version":"networkpolicy-calico-1.0.1"},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile","kubernetes.io/cluster-service":"true"},"name":"blockaffinities.crd.projectcalico.org"},"spec":{"group":"crd.projectcalico.org","names":{"kind":"BlockAffinity","plural":"blockaffinities","singular":"blockaffinity"},"scope":"Cluster","version":"v1"}}
  creationTimestamp: "2020-02-05T08:41:58Z"
  generation: 1
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/cluster-service: "true"
  name: blockaffinities.crd.projectcalico.org
  resourceVersion: "84913740"
  selfLink: /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/blockaffinities.crd.projectcalico.org
  uid: 2e006d3d-f30e-47f0-b674-bdbb7c544f86
spec:
  conversion:
    strategy: None
  group: crd.projectcalico.org
  names:
    kind: BlockAffinity
    listKind: BlockAffinityList
    plural: blockaffinities
    singular: blockaffinity
  preserveUnknownFields: true
  scope: Cluster
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
status:
  acceptedNames:
    kind: BlockAffinity
    listKind: BlockAffinityList
    plural: blockaffinities
    singular: blockaffinity
  conditions:
  - lastTransitionTime: "2020-02-05T08:41:58Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: null
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1
