apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: "2019-08-29T15:34:46Z"
  generation: 3
  name: backendconfigs.cloud.google.com
  resourceVersion: "84915585"
  selfLink: /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/backendconfigs.cloud.google.com
  uid: 87c3132e-ca72-11e9-8439-4201ac100008
spec:
  conversion:
    strategy: None
  group: cloud.google.com
  names:
    kind: BackendConfig
    listKind: BackendConfigList
    plural: backendconfigs
    singular: backendconfig
  preserveUnknownFields: true
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: BackendConfigSpec is the spec for a BackendConfig resource
          properties:
            cdn:
              description: CDNConfig contains configuration for CDN-enabled backends.
              properties:
                cachePolicy:
                  description: CacheKeyPolicy contains configuration for how requests
                    to a CDN-enabled backend are cached.
                  properties:
                    includeHost:
                      description: If true, requests to different hosts will be cached
                        separately.
                      type: boolean
                    includeProtocol:
                      description: If true, http and https requests will be cached
                        separately.
                      type: boolean
                    includeQueryString:
                      description: If true, query string parameters are included in
                        the cache key according to QueryStringBlacklist and QueryStringWhitelist.
                        If neither is set, the entire query string is included and
                        if false the entire query string is excluded.
                      type: boolean
                    queryStringBlacklist:
                      description: Names of query strint parameters to exclude from
                        cache keys. All other parameters are included. Either specify
                        QueryStringBlacklist or QueryStringWhitelist, but not both.
                      items:
                        type: string
                      type: array
                    queryStringWhitelist:
                      description: Names of query string parameters to include in
                        cache keys. All other parameters are excluded. Either specify
                        QueryStringBlacklist or QueryStringWhitelist, but not both.
                      items:
                        type: string
                      type: array
                  type: object
                enabled:
                  type: boolean
              required:
              - enabled
              type: object
            connectionDraining:
              description: ConnectionDrainingConfig contains configuration for connection
                draining. For now the draining timeout. May manage more settings in
                the future.
              properties:
                drainingTimeoutSec:
                  description: Draining timeout in seconds.
                  format: int64
                  type: integer
              type: object
            customRequestHeaders:
              description: CustomRequestHeadersConfig contains configuration for custom
                request headers
              properties:
                headers:
                  items:
                    type: string
                  type: array
              type: object
            iap:
              description: IAPConfig contains configuration for IAP-enabled backends.
              properties:
                enabled:
                  type: boolean
                oauthclientCredentials:
                  description: OAuthClientCredentials contains credentials for a single
                    IAP-enabled backend.
                  properties:
                    clientID:
                      description: Direct reference to OAuth client id.
                      type: string
                    clientSecret:
                      description: Direct reference to OAuth client secret.
                      type: string
                    secretName:
                      description: The name of a k8s secret which stores the OAuth
                        client id & secret.
                      type: string
                  required:
                  - secretName
                  type: object
              required:
              - enabled
              - oauthclientCredentials
              type: object
            securityPolicy:
              type: object
            sessionAffinity:
              description: SessionAffinityConfig contains configuration for stickyness
                parameters.
              properties:
                affinityCookieTtlSec:
                  format: int64
                  type: integer
                affinityType:
                  type: string
              type: object
            timeoutSec:
              format: int64
              type: integer
          type: object
        status:
          type: object
      type: object
  version: v1beta1
  versions:
  - name: v1beta1
    served: true
    storage: true
status:
  acceptedNames:
    kind: BackendConfig
    listKind: BackendConfigList
    plural: backendconfigs
    singular: backendconfig
  conditions:
  - lastTransitionTime: "2019-08-29T15:34:46Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: null
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1beta1
