apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    helm.sh/resource-policy: keep
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apiextensions.k8s.io/v1beta1","kind":"CustomResourceDefinition","metadata":{"annotations":{"helm.sh/resource-policy":"keep"},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile","app":"certmanager","chart":"certmanager","heritage":"Tiller","k8s-app":"istio","release":"istio"},"name":"clusterissuers.certmanager.k8s.io"},"spec":{"group":"certmanager.k8s.io","names":{"kind":"ClusterIssuer","plural":"clusterissuers"},"scope":"Cluster","version":"v1alpha1"}}
  creationTimestamp: "2019-08-30T09:23:41Z"
  generation: 8
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    app: certmanager
    chart: certmanager
    heritage: Tiller
    k8s-app: istio
    release: istio
  name: clusterissuers.certmanager.k8s.io
  resourceVersion: "30697478"
  selfLink: /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/clusterissuers.certmanager.k8s.io
  uid: db2fc339-cb07-11e9-a4ee-4201ac10000b
spec:
  conversion:
    strategy: None
  group: certmanager.k8s.io
  names:
    kind: ClusterIssuer
    listKind: ClusterIssuerList
    plural: clusterissuers
    singular: clusterissuer
  preserveUnknownFields: true
  scope: Cluster
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ClusterIssuer
    listKind: ClusterIssuerList
    plural: clusterissuers
    singular: clusterissuer
  conditions:
  - lastTransitionTime: "2019-08-30T09:23:41Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: null
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1alpha1
