apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apiextensions.k8s.io/v1beta1","kind":"CustomResourceDefinition","metadata":{"annotations":{},"labels":{"app":"kiali","version":"v1.4.2"},"name":"monitoringdashboards.monitoring.kiali.io"},"spec":{"group":"monitoring.kiali.io","names":{"kind":"MonitoringDashboard","listKind":"MonitoringDashboardList","plural":"monitoringdashboards","singular":"monitoringdashboard"},"scope":"Namespaced","version":"v1alpha1"}}
  creationTimestamp: "2019-08-30T12:04:21Z"
  generation: 1
  labels:
    app: kiali
    version: v1.4.2
  name: monitoringdashboards.monitoring.kiali.io
  resourceVersion: "6717167"
  selfLink: /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/monitoringdashboards.monitoring.kiali.io
  uid: 4d609a37-cb1e-11e9-917e-4201ac100009
spec:
  conversion:
    strategy: None
  group: monitoring.kiali.io
  names:
    kind: MonitoringDashboard
    listKind: MonitoringDashboardList
    plural: monitoringdashboards
    singular: monitoringdashboard
  preserveUnknownFields: true
  scope: Namespaced
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: MonitoringDashboard
    listKind: MonitoringDashboardList
    plural: monitoringdashboards
    singular: monitoringdashboard
  conditions:
  - lastTransitionTime: "2019-08-30T12:04:21Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: null
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1alpha1
