apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apiextensions.k8s.io/v1beta1","kind":"CustomResourceDefinition","metadata":{"annotations":{},"labels":{"app":"kiali-operator","version":"v1.4.2"},"name":"kialis.kiali.io"},"spec":{"group":"kiali.io","names":{"kind":"Kiali","listKind":"KialiList","plural":"kialis","singular":"kiali"},"scope":"Namespaced","subresources":{"status":{}},"version":"v1alpha1","versions":[{"name":"v1alpha1","served":true,"storage":true}]}}
  creationTimestamp: "2019-08-30T12:04:21Z"
  generation: 1
  labels:
    app: kiali-operator
    version: v1.4.2
  name: kialis.kiali.io
  resourceVersion: "6717165"
  selfLink: /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/kialis.kiali.io
  uid: 4d5f0f9f-cb1e-11e9-917e-4201ac100009
spec:
  conversion:
    strategy: None
  group: kiali.io
  names:
    kind: Kiali
    listKind: KialiList
    plural: kialis
    singular: kiali
  preserveUnknownFields: true
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: Kiali
    listKind: KialiList
    plural: kialis
    singular: kiali
  conditions:
  - lastTransitionTime: "2019-08-30T12:04:21Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: null
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1alpha1
