apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    helm.sh/resource-policy: keep
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apiextensions.k8s.io/v1beta1","kind":"CustomResourceDefinition","metadata":{"annotations":{"helm.sh/resource-policy":"keep"},"labels":{"app.kubernetes.io/instance":"sealed-secrets","app.kubernetes.io/managed-by":"Tiller","app.kubernetes.io/name":"sealed-secrets","app.kubernetes.io/version":"0.9.6","helm.sh/chart":"sealedsecrets-1.6.1"},"name":"sealedsecrets.bitnami.com"},"spec":{"group":"bitnami.com","names":{"kind":"SealedSecret","listKind":"SealedSecretList","plural":"sealedsecrets","singular":"sealedsecret"},"scope":"Namespaced","version":"v1alpha1"}}
  creationTimestamp: "2019-09-05T11:18:44Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: sealed-secrets
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: sealed-secrets
    app.kubernetes.io/version: 0.9.6
    helm.sh/chart: sealedsecrets-1.6.1
  name: sealedsecrets.bitnami.com
  resourceVersion: "51433516"
  selfLink: /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/sealedsecrets.bitnami.com
  uid: ec46ecba-cfce-11e9-b7ff-4201ac10000a
spec:
  conversion:
    strategy: None
  group: bitnami.com
  names:
    kind: SealedSecret
    listKind: SealedSecretList
    plural: sealedsecrets
    singular: sealedsecret
  preserveUnknownFields: true
  scope: Namespaced
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: SealedSecret
    listKind: SealedSecretList
    plural: sealedsecrets
    singular: sealedsecret
  conditions:
  - lastTransitionTime: "2019-09-05T11:18:44Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: null
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1alpha1
