apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    components.gke.io/component-version: networkpolicy-calico-1.0.1
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apiextensions.k8s.io/v1beta1","kind":"CustomResourceDefinition","metadata":{"annotations":{"components.gke.io/component-version":"networkpolicy-calico-1.0.1"},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile","kubernetes.io/cluster-service":"true"},"name":"ipamhandles.crd.projectcalico.org"},"spec":{"group":"crd.projectcalico.org","names":{"kind":"IPAMHandle","plural":"ipamhandles","singular":"ipamhandle"},"scope":"Cluster","version":"v1"}}
  creationTimestamp: "2020-02-05T08:41:59Z"
  generation: 1
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/cluster-service: "true"
  name: ipamhandles.crd.projectcalico.org
  resourceVersion: "84913761"
  selfLink: /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/ipamhandles.crd.projectcalico.org
  uid: 4783b962-d7a1-4006-8d4a-5b90a178b1c2
spec:
  conversion:
    strategy: None
  group: crd.projectcalico.org
  names:
    kind: IPAMHandle
    listKind: IPAMHandleList
    plural: ipamhandles
    singular: ipamhandle
  preserveUnknownFields: true
  scope: Cluster
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
status:
  acceptedNames:
    kind: IPAMHandle
    listKind: IPAMHandleList
    plural: ipamhandles
    singular: ipamhandle
  conditions:
  - lastTransitionTime: "2020-02-05T08:41:59Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: null
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1
