apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    cnrm.cloud.google.com/version: 1.5.0
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apiextensions.k8s.io/v1beta1","kind":"CustomResourceDefinition","metadata":{"annotations":{"cnrm.cloud.google.com/version":"1.5.0"},"creationTimestamp":null,"labels":{"cnrm.cloud.google.com/managed-by-kcc":"true","cnrm.cloud.google.com/system":"true","cnrm.cloud.google.com/tf2crd":"true"},"name":"computesslpolicies.compute.cnrm.cloud.google.com"},"spec":{"group":"compute.cnrm.cloud.google.com","names":{"categories":["gcp"],"kind":"ComputeSSLPolicy","plural":"computesslpolicies","shortNames":["gcpcomputesslpolicy","gcpcomputesslpolicies"],"singular":"computesslpolicy"},"scope":"Namespaced","validation":{"openAPIV3Schema":{"properties":{"apiVersion":{"description":"apiVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources","type":"string"},"kind":{"description":"kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds","type":"string"},"metadata":{"type":"object"},"spec":{"properties":{"customFeatures":{"description":"Profile specifies the set of SSL features that can be used by the\nload balancer when negotiating SSL with clients. This can be one of\n'COMPATIBLE', 'MODERN', 'RESTRICTED', or 'CUSTOM'. If using 'CUSTOM',\nthe set of SSL features to enable must be specified in the\n'customFeatures' field.\n\nSee the [official documentation](https://cloud.google.com/compute/docs/load-balancing/ssl-policies#profilefeaturesupport)\nfor which ciphers are available to use. **Note**: this argument\n*must* be present when using the 'CUSTOM' profile. This argument\n*must not* be present when using any other profile.","items":{"type":"string"},"type":"array"},"description":{"description":"An optional description of this resource.","type":"string"},"minTlsVersion":{"description":"The minimum version of SSL protocol that can be used by the clients\nto establish a connection with the load balancer. This can be one of\n'TLS_1_0', 'TLS_1_1', 'TLS_1_2'.\n Default is 'TLS_1_0'.","type":"string"},"profile":{"description":"Profile specifies the set of SSL features that can be used by the\nload balancer when negotiating SSL with clients. This can be one of\n'COMPATIBLE', 'MODERN', 'RESTRICTED', or 'CUSTOM'. If using 'CUSTOM',\nthe set of SSL features to enable must be specified in the\n'customFeatures' field.\n\nSee the [official documentation](https://cloud.google.com/compute/docs/load-balancing/ssl-policies#profilefeaturesupport)\nfor information on what cipher suites each profile provides. If\n'CUSTOM' is used, the 'custom_features' attribute **must be set**.\nDefault is 'COMPATIBLE'.","type":"string"}},"type":"object"},"status":{"properties":{"conditions":{"description":"Conditions represents the latest available observation of the resource's current state.","items":{"properties":{"lastTransitionTime":{"description":"Last time the condition transitioned from one status to another.","type":"string"},"message":{"description":"Human-readable message indicating details about last transition.","type":"string"},"reason":{"description":"Unique, one-word, CamelCase reason for the condition's last transition.","type":"string"},"status":{"description":"Status is the status of the condition. Can be True, False, Unknown.","type":"string"},"type":{"description":"Type is the type of the condition.","type":"string"}},"type":"object"},"type":"array"},"creationTimestamp":{"description":"Creation timestamp in RFC3339 text format.","type":"string"},"enabledFeatures":{"description":"The list of features enabled in the SSL policy.","items":{"type":"string"},"type":"array"},"fingerprint":{"description":"Fingerprint of this resource. A hash of the contents stored in this\nobject. This field is used in optimistic locking.","type":"string"},"selfLink":{"type":"string"}},"type":"object"}},"type":"object"}},"version":"v1beta1"},"status":{"acceptedNames":{"kind":"","plural":""},"conditions":[],"storedVersions":[]}}
  creationTimestamp: "2020-03-20T15:03:05Z"
  generation: 1
  labels:
    cnrm.cloud.google.com/managed-by-kcc: "true"
    cnrm.cloud.google.com/system: "true"
    cnrm.cloud.google.com/tf2crd: "true"
  name: computesslpolicies.compute.cnrm.cloud.google.com
  resourceVersion: "113849412"
  selfLink: /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/computesslpolicies.compute.cnrm.cloud.google.com
  uid: b0e94fcb-15c0-432c-913e-a24e07bee41e
spec:
  conversion:
    strategy: None
  group: compute.cnrm.cloud.google.com
  names:
    categories:
    - gcp
    kind: ComputeSSLPolicy
    listKind: ComputeSSLPolicyList
    plural: computesslpolicies
    shortNames:
    - gcpcomputesslpolicy
    - gcpcomputesslpolicies
    singular: computesslpolicy
  preserveUnknownFields: true
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'apiVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            customFeatures:
              description: |-
                Profile specifies the set of SSL features that can be used by the
                load balancer when negotiating SSL with clients. This can be one of
                'COMPATIBLE', 'MODERN', 'RESTRICTED', or 'CUSTOM'. If using 'CUSTOM',
                the set of SSL features to enable must be specified in the
                'customFeatures' field.

                See the [official documentation](https://cloud.google.com/compute/docs/load-balancing/ssl-policies#profilefeaturesupport)
                for which ciphers are available to use. **Note**: this argument
                *must* be present when using the 'CUSTOM' profile. This argument
                *must not* be present when using any other profile.
              items:
                type: string
              type: array
            description:
              description: An optional description of this resource.
              type: string
            minTlsVersion:
              description: |-
                The minimum version of SSL protocol that can be used by the clients
                to establish a connection with the load balancer. This can be one of
                'TLS_1_0', 'TLS_1_1', 'TLS_1_2'.
                 Default is 'TLS_1_0'.
              type: string
            profile:
              description: |-
                Profile specifies the set of SSL features that can be used by the
                load balancer when negotiating SSL with clients. This can be one of
                'COMPATIBLE', 'MODERN', 'RESTRICTED', or 'CUSTOM'. If using 'CUSTOM',
                the set of SSL features to enable must be specified in the
                'customFeatures' field.

                See the [official documentation](https://cloud.google.com/compute/docs/load-balancing/ssl-policies#profilefeaturesupport)
                for information on what cipher suites each profile provides. If
                'CUSTOM' is used, the 'custom_features' attribute **must be set**.
                Default is 'COMPATIBLE'.
              type: string
          type: object
        status:
          properties:
            conditions:
              description: Conditions represents the latest available observation
                of the resource's current state.
              items:
                properties:
                  lastTransitionTime:
                    description: Last time the condition transitioned from one status
                      to another.
                    type: string
                  message:
                    description: Human-readable message indicating details about last
                      transition.
                    type: string
                  reason:
                    description: Unique, one-word, CamelCase reason for the condition's
                      last transition.
                    type: string
                  status:
                    description: Status is the status of the condition. Can be True,
                      False, Unknown.
                    type: string
                  type:
                    description: Type is the type of the condition.
                    type: string
                type: object
              type: array
            creationTimestamp:
              description: Creation timestamp in RFC3339 text format.
              type: string
            enabledFeatures:
              description: The list of features enabled in the SSL policy.
              items:
                type: string
              type: array
            fingerprint:
              description: |-
                Fingerprint of this resource. A hash of the contents stored in this
                object. This field is used in optimistic locking.
              type: string
            selfLink:
              type: string
          type: object
      type: object
  version: v1beta1
  versions:
  - name: v1beta1
    served: true
    storage: true
status:
  acceptedNames:
    categories:
    - gcp
    kind: ComputeSSLPolicy
    listKind: ComputeSSLPolicyList
    plural: computesslpolicies
    shortNames:
    - gcpcomputesslpolicy
    - gcpcomputesslpolicies
    singular: computesslpolicy
  conditions:
  - lastTransitionTime: "2020-03-20T15:03:05Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: null
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1beta1
