apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apiextensions.k8s.io/v1beta1","kind":"CustomResourceDefinition","metadata":{"annotations":{},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile"},"name":"updateinfos.nodemanagement.gke.io"},"spec":{"group":"nodemanagement.gke.io","names":{"kind":"UpdateInfo","plural":"updateinfos","shortNames":["updinf"],"singular":"updateinfo"},"scope":"Namespaced","validation":{"openAPIV3Schema":{"properties":{"spec":{"properties":{"ValidUntil":{"type":"date"},"surgeNode":{"type":"string"},"targetNode":{"type":"string"},"type":{"type":"string"}},"type":"object"}},"type":"object"}},"versions":[{"name":"v1alpha1","served":true,"storage":true}]}}
  creationTimestamp: "2019-09-10T09:03:53Z"
  generation: 2
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
  name: updateinfos.nodemanagement.gke.io
  resourceVersion: "104590717"
  selfLink: /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/updateinfos.nodemanagement.gke.io
  uid: e9747142-d3a9-11e9-8873-4201ac100009
spec:
  conversion:
    strategy: None
  group: nodemanagement.gke.io
  names:
    kind: UpdateInfo
    listKind: UpdateInfoList
    plural: updateinfos
    shortNames:
    - updinf
    singular: updateinfo
  preserveUnknownFields: true
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            ValidUntil:
              type: date
            surgeNode:
              type: string
            targetNode:
              type: string
            type:
              type: string
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: UpdateInfo
    listKind: UpdateInfoList
    plural: updateinfos
    shortNames:
    - updinf
    singular: updateinfo
  conditions:
  - lastTransitionTime: "2019-09-10T09:03:53Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: null
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1alpha1
