apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: "2020-01-10T11:06:04Z"
  generation: 1
  name: sourcecoderepositories.project.cattle.io
  resourceVersion: "68514866"
  selfLink: /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/sourcecoderepositories.project.cattle.io
  uid: 317b3dd2-3399-11ea-834d-4201ac100006
spec:
  conversion:
    strategy: None
  group: project.cattle.io
  names:
    kind: SourceCodeRepository
    listKind: SourceCodeRepositoryList
    plural: sourcecoderepositories
    singular: sourcecoderepository
  preserveUnknownFields: true
  scope: Namespaced
  version: v3
  versions:
  - name: v3
    served: true
    storage: true
status:
  acceptedNames:
    kind: SourceCodeRepository
    listKind: SourceCodeRepositoryList
    plural: sourcecoderepositories
    singular: sourcecoderepository
  conditions:
  - lastTransitionTime: "2020-01-10T11:06:04Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: null
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v3
