apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    helm.sh/resource-policy: keep
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apiextensions.k8s.io/v1beta1","kind":"CustomResourceDefinition","metadata":{"annotations":{"helm.sh/resource-policy":"keep"},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile","app":"istio-citadel","chart":"istio","heritage":"Tiller","k8s-app":"istio","release":"istio"},"name":"meshpolicies.authentication.istio.io"},"spec":{"group":"authentication.istio.io","names":{"categories":["istio-io","authentication-istio-io"],"kind":"MeshPolicy","listKind":"MeshPolicyList","plural":"meshpolicies","singular":"meshpolicy"},"scope":"Cluster","version":"v1alpha1"}}
  creationTimestamp: "2019-08-29T16:02:23Z"
  generation: 2
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    app: istio-citadel
    chart: istio
    heritage: Tiller
    k8s-app: istio
    release: istio
  name: meshpolicies.authentication.istio.io
  resourceVersion: "27414097"
  selfLink: /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/meshpolicies.authentication.istio.io
  uid: 633de630-ca76-11e9-a23c-4201ac100009
spec:
  additionalPrinterColumns:
  - JSONPath: .metadata.creationTimestamp
    description: |-
      CreationTimestamp is a timestamp representing the server time when this object was created. It is not guaranteed to be set in happens-before order across separate operations. Clients may not set this value. It is represented in RFC3339 form and is in UTC.

      Populated by the system. Read-only. Null for lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata
    name: Age
    type: date
  conversion:
    strategy: None
  group: authentication.istio.io
  names:
    categories:
    - istio-io
    - authentication-istio-io
    kind: MeshPolicy
    listKind: MeshPolicyList
    plural: meshpolicies
    singular: meshpolicy
  preserveUnknownFields: true
  scope: Cluster
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    categories:
    - istio-io
    - authentication-istio-io
    kind: MeshPolicy
    listKind: MeshPolicyList
    plural: meshpolicies
    singular: meshpolicy
  conditions:
  - lastTransitionTime: "2019-08-29T16:02:23Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: null
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1alpha1
