apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    cnrm.cloud.google.com/version: 1.5.0
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apiextensions.k8s.io/v1beta1","kind":"CustomResourceDefinition","metadata":{"annotations":{"cnrm.cloud.google.com/version":"1.5.0"},"creationTimestamp":null,"labels":{"cnrm.cloud.google.com/managed-by-kcc":"true","cnrm.cloud.google.com/system":"true","cnrm.cloud.google.com/tf2crd":"true"},"name":"computeexternalvpngateways.compute.cnrm.cloud.google.com"},"spec":{"group":"compute.cnrm.cloud.google.com","names":{"categories":["gcp"],"kind":"ComputeExternalVPNGateway","plural":"computeexternalvpngateways","shortNames":["gcpcomputeexternalvpngateway","gcpcomputeexternalvpngateways"],"singular":"computeexternalvpngateway"},"scope":"Namespaced","validation":{"openAPIV3Schema":{"properties":{"apiVersion":{"description":"apiVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources","type":"string"},"kind":{"description":"kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds","type":"string"},"metadata":{"type":"object"},"spec":{"properties":{"description":{"description":"An optional description of this resource.","type":"string"},"interface":{"description":"A list of interfaces on this external VPN gateway.","items":{"properties":{"id":{"description":"The numberic ID for this interface. Allowed values are based on the redundancy type\nof this external VPN gateway\n* '0 - SINGLE_IP_INTERNALLY_REDUNDANT'\n* '0, 1 - TWO_IPS_REDUNDANCY'\n* '0, 1, 2, 3 - FOUR_IPS_REDUNDANCY'","type":"integer"},"ipAddress":{"description":"IP address of the interface in the external VPN gateway.\nOnly IPv4 is supported. This IP address can be either from\nyour on-premise gateway or another Cloud provider’s VPN gateway,\nit cannot be an IP address from Google Compute Engine.","type":"string"}},"type":"object"},"type":"array"},"redundancyType":{"description":"Indicates the redundancy type of this external VPN gateway","type":"string"}},"type":"object"},"status":{"properties":{"conditions":{"description":"Conditions represents the latest available observation of the resource's current state.","items":{"properties":{"lastTransitionTime":{"description":"Last time the condition transitioned from one status to another.","type":"string"},"message":{"description":"Human-readable message indicating details about last transition.","type":"string"},"reason":{"description":"Unique, one-word, CamelCase reason for the condition's last transition.","type":"string"},"status":{"description":"Status is the status of the condition. Can be True, False, Unknown.","type":"string"},"type":{"description":"Type is the type of the condition.","type":"string"}},"type":"object"},"type":"array"},"selfLink":{"type":"string"}},"type":"object"}},"type":"object"}},"version":"v1beta1"},"status":{"acceptedNames":{"kind":"","plural":""},"conditions":[],"storedVersions":[]}}
  creationTimestamp: "2020-03-20T15:02:59Z"
  generation: 1
  labels:
    cnrm.cloud.google.com/managed-by-kcc: "true"
    cnrm.cloud.google.com/system: "true"
    cnrm.cloud.google.com/tf2crd: "true"
  name: computeexternalvpngateways.compute.cnrm.cloud.google.com
  resourceVersion: "113849292"
  selfLink: /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/computeexternalvpngateways.compute.cnrm.cloud.google.com
  uid: 23a8a4ac-6db7-4a95-978b-e902e7c82807
spec:
  conversion:
    strategy: None
  group: compute.cnrm.cloud.google.com
  names:
    categories:
    - gcp
    kind: ComputeExternalVPNGateway
    listKind: ComputeExternalVPNGatewayList
    plural: computeexternalvpngateways
    shortNames:
    - gcpcomputeexternalvpngateway
    - gcpcomputeexternalvpngateways
    singular: computeexternalvpngateway
  preserveUnknownFields: true
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'apiVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            description:
              description: An optional description of this resource.
              type: string
            interface:
              description: A list of interfaces on this external VPN gateway.
              items:
                properties:
                  id:
                    description: |-
                      The numberic ID for this interface. Allowed values are based on the redundancy type
                      of this external VPN gateway
                      * '0 - SINGLE_IP_INTERNALLY_REDUNDANT'
                      * '0, 1 - TWO_IPS_REDUNDANCY'
                      * '0, 1, 2, 3 - FOUR_IPS_REDUNDANCY'
                    type: integer
                  ipAddress:
                    description: |-
                      IP address of the interface in the external VPN gateway.
                      Only IPv4 is supported. This IP address can be either from
                      your on-premise gateway or another Cloud provider’s VPN gateway,
                      it cannot be an IP address from Google Compute Engine.
                    type: string
                type: object
              type: array
            redundancyType:
              description: Indicates the redundancy type of this external VPN gateway
              type: string
          type: object
        status:
          properties:
            conditions:
              description: Conditions represents the latest available observation
                of the resource's current state.
              items:
                properties:
                  lastTransitionTime:
                    description: Last time the condition transitioned from one status
                      to another.
                    type: string
                  message:
                    description: Human-readable message indicating details about last
                      transition.
                    type: string
                  reason:
                    description: Unique, one-word, CamelCase reason for the condition's
                      last transition.
                    type: string
                  status:
                    description: Status is the status of the condition. Can be True,
                      False, Unknown.
                    type: string
                  type:
                    description: Type is the type of the condition.
                    type: string
                type: object
              type: array
            selfLink:
              type: string
          type: object
      type: object
  version: v1beta1
  versions:
  - name: v1beta1
    served: true
    storage: true
status:
  acceptedNames:
    categories:
    - gcp
    kind: ComputeExternalVPNGateway
    listKind: ComputeExternalVPNGatewayList
    plural: computeexternalvpngateways
    shortNames:
    - gcpcomputeexternalvpngateway
    - gcpcomputeexternalvpngateways
    singular: computeexternalvpngateway
  conditions:
  - lastTransitionTime: "2020-03-20T15:02:59Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: null
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1beta1
