apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    helm.sh/resource-policy: keep
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apiextensions.k8s.io/v1beta1","kind":"CustomResourceDefinition","metadata":{"annotations":{"helm.sh/resource-policy":"keep"},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile","app":"certmanager","chart":"certmanager","heritage":"Tiller","k8s-app":"istio","release":"istio"},"name":"orders.certmanager.k8s.io"},"spec":{"additionalPrinterColumns":[{"JSONPath":".status.state","name":"State","type":"string"},{"JSONPath":".spec.issuerRef.name","name":"Issuer","priority":1,"type":"string"},{"JSONPath":".status.reason","name":"Reason","priority":1,"type":"string"},{"JSONPath":".metadata.creationTimestamp","description":"CreationTimestamp is a timestamp representing the server time when this object was created. It is not guaranteed to be set in happens-before order across separate operations. Clients may not set this value. It is represented in RFC3339 form and is in UTC.\n\nPopulated by the system. Read-only. Null for lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata","name":"Age","type":"date"}],"group":"certmanager.k8s.io","names":{"kind":"Order","plural":"orders"},"scope":"Namespaced","version":"v1alpha1"}}
  creationTimestamp: "2019-08-30T09:23:41Z"
  generation: 8
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    app: certmanager
    chart: certmanager
    heritage: Tiller
    k8s-app: istio
    release: istio
  name: orders.certmanager.k8s.io
  resourceVersion: "30697536"
  selfLink: /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/orders.certmanager.k8s.io
  uid: db14f7a2-cb07-11e9-a4ee-4201ac10000b
spec:
  additionalPrinterColumns:
  - JSONPath: .status.state
    name: State
    type: string
  - JSONPath: .spec.issuerRef.name
    name: Issuer
    priority: 1
    type: string
  - JSONPath: .status.reason
    name: Reason
    priority: 1
    type: string
  - JSONPath: .metadata.creationTimestamp
    description: |-
      CreationTimestamp is a timestamp representing the server time when this object was created. It is not guaranteed to be set in happens-before order across separate operations. Clients may not set this value. It is represented in RFC3339 form and is in UTC.

      Populated by the system. Read-only. Null for lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata
    name: Age
    type: date
  conversion:
    strategy: None
  group: certmanager.k8s.io
  names:
    kind: Order
    listKind: OrderList
    plural: orders
    singular: order
  preserveUnknownFields: true
  scope: Namespaced
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: Order
    listKind: OrderList
    plural: orders
    singular: order
  conditions:
  - lastTransitionTime: "2019-08-30T09:23:41Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: null
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1alpha1
