apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    cnrm.cloud.google.com/version: 1.5.0
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apiextensions.k8s.io/v1beta1","kind":"CustomResourceDefinition","metadata":{"annotations":{"cnrm.cloud.google.com/version":"1.5.0"},"creationTimestamp":null,"labels":{"cnrm.cloud.google.com/managed-by-kcc":"true","cnrm.cloud.google.com/system":"true","cnrm.cloud.google.com/tf2crd":"true"},"name":"spannerinstances.spanner.cnrm.cloud.google.com"},"spec":{"group":"spanner.cnrm.cloud.google.com","names":{"categories":["gcp"],"kind":"SpannerInstance","plural":"spannerinstances","shortNames":["gcpspannerinstance","gcpspannerinstances"],"singular":"spannerinstance"},"scope":"Namespaced","validation":{"openAPIV3Schema":{"properties":{"apiVersion":{"description":"apiVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources","type":"string"},"kind":{"description":"kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds","type":"string"},"metadata":{"type":"object"},"spec":{"properties":{"config":{"description":"The name of the instance's configuration (similar but not\nquite the same as a region) which defines defines the geographic placement and\nreplication of your databases in this instance. It determines where your data\nis stored. Values are typically of the form 'regional-europe-west1' , 'us-central' etc.\nIn order to obtain a valid list please consult the\n[Configuration section of the docs](https://cloud.google.com/spanner/docs/instances).","type":"string"},"displayName":{"description":"The descriptive name for this instance as it appears in UIs. Must be\nunique per project and between 4 and 30 characters in length.","type":"string"},"numNodes":{"description":"The number of nodes allocated to this instance.","type":"integer"}},"required":["config","displayName"],"type":"object"},"status":{"properties":{"conditions":{"description":"Conditions represents the latest available observation of the resource's current state.","items":{"properties":{"lastTransitionTime":{"description":"Last time the condition transitioned from one status to another.","type":"string"},"message":{"description":"Human-readable message indicating details about last transition.","type":"string"},"reason":{"description":"Unique, one-word, CamelCase reason for the condition's last transition.","type":"string"},"status":{"description":"Status is the status of the condition. Can be True, False, Unknown.","type":"string"},"type":{"description":"Type is the type of the condition.","type":"string"}},"type":"object"},"type":"array"},"state":{"description":"Instance status: 'CREATING' or 'READY'.","type":"string"}},"type":"object"}},"required":["spec"],"type":"object"}},"version":"v1beta1"},"status":{"acceptedNames":{"kind":"","plural":""},"conditions":[],"storedVersions":[]}}
  creationTimestamp: "2020-03-20T15:03:17Z"
  generation: 1
  labels:
    cnrm.cloud.google.com/managed-by-kcc: "true"
    cnrm.cloud.google.com/system: "true"
    cnrm.cloud.google.com/tf2crd: "true"
  name: spannerinstances.spanner.cnrm.cloud.google.com
  resourceVersion: "113849609"
  selfLink: /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/spannerinstances.spanner.cnrm.cloud.google.com
  uid: c8713738-6965-446f-9cb9-b2bb68c3befe
spec:
  conversion:
    strategy: None
  group: spanner.cnrm.cloud.google.com
  names:
    categories:
    - gcp
    kind: SpannerInstance
    listKind: SpannerInstanceList
    plural: spannerinstances
    shortNames:
    - gcpspannerinstance
    - gcpspannerinstances
    singular: spannerinstance
  preserveUnknownFields: true
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'apiVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            config:
              description: |-
                The name of the instance's configuration (similar but not
                quite the same as a region) which defines defines the geographic placement and
                replication of your databases in this instance. It determines where your data
                is stored. Values are typically of the form 'regional-europe-west1' , 'us-central' etc.
                In order to obtain a valid list please consult the
                [Configuration section of the docs](https://cloud.google.com/spanner/docs/instances).
              type: string
            displayName:
              description: |-
                The descriptive name for this instance as it appears in UIs. Must be
                unique per project and between 4 and 30 characters in length.
              type: string
            numNodes:
              description: The number of nodes allocated to this instance.
              type: integer
          required:
          - config
          - displayName
          type: object
        status:
          properties:
            conditions:
              description: Conditions represents the latest available observation
                of the resource's current state.
              items:
                properties:
                  lastTransitionTime:
                    description: Last time the condition transitioned from one status
                      to another.
                    type: string
                  message:
                    description: Human-readable message indicating details about last
                      transition.
                    type: string
                  reason:
                    description: Unique, one-word, CamelCase reason for the condition's
                      last transition.
                    type: string
                  status:
                    description: Status is the status of the condition. Can be True,
                      False, Unknown.
                    type: string
                  type:
                    description: Type is the type of the condition.
                    type: string
                type: object
              type: array
            state:
              description: 'Instance status: ''CREATING'' or ''READY''.'
              type: string
          type: object
      required:
      - spec
      type: object
  version: v1beta1
  versions:
  - name: v1beta1
    served: true
    storage: true
status:
  acceptedNames:
    categories:
    - gcp
    kind: SpannerInstance
    listKind: SpannerInstanceList
    plural: spannerinstances
    shortNames:
    - gcpspannerinstance
    - gcpspannerinstances
    singular: spannerinstance
  conditions:
  - lastTransitionTime: "2020-03-20T15:03:17Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: null
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1beta1
