apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    components.gke.io/component-version: networkpolicy-calico-1.0.1
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apiextensions.k8s.io/v1beta1","kind":"CustomResourceDefinition","metadata":{"annotations":{"components.gke.io/component-version":"networkpolicy-calico-1.0.1"},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile","kubernetes.io/cluster-service":"true"},"name":"networksets.crd.projectcalico.org"},"spec":{"group":"crd.projectcalico.org","names":{"kind":"NetworkSet","plural":"networksets","singular":"networkset"},"scope":"Namespaced","version":"v1"}}
  creationTimestamp: "2020-02-05T08:41:59Z"
  generation: 1
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/cluster-service: "true"
  name: networksets.crd.projectcalico.org
  resourceVersion: "84913767"
  selfLink: /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/networksets.crd.projectcalico.org
  uid: b8ccde2e-7692-4014-a230-8f9f4692b95b
spec:
  conversion:
    strategy: None
  group: crd.projectcalico.org
  names:
    kind: NetworkSet
    listKind: NetworkSetList
    plural: networksets
    singular: networkset
  preserveUnknownFields: true
  scope: Namespaced
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
status:
  acceptedNames:
    kind: NetworkSet
    listKind: NetworkSetList
    plural: networksets
    singular: networkset
  conditions:
  - lastTransitionTime: "2020-02-05T08:41:59Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: null
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1
